# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: CI

on: [push]

jobs:
  check_dawn:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: "shopify/dawn"
          path: "./dawn"

      - name: Theme Check
        uses: ./
        id: theme-check-action
        with:
          theme_root: './dawn'
